# Copyright (C) 2026 Garudex Labs.  All Rights Reserved.
# Caracal, a product of Garudex Labs
#
# PostgreSQL 18 base image for Caracal local dev. Schema migrations are applied by the API at boot.

FROM postgres:18-alpine

ENV POSTGRES_DB=caracal

EXPOSE 5432
